ClassDemoPizzaApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ClassDemoPizzaApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ClassDemoPizzaApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ClassDemoPizzaApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ClassDemoPizzaApp/Pages/Pizzas/Delete.cshtml.cs
using ClassDemoPizzaApp.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLib.model;

namespace ClassDemoPizzaApp.Pages.Pizzas
{
    public class DeleteModel : PageModel
    {
        /*
         * modtage dependency injection
         */
        private IPizzaRepositoryService _service;

        public DeleteModel(IPizzaRepositoryService service)
        {
            _service = service;
        }


        /*
         * Properties til viewet
         */

        public Pizza Pizza { get; set; }

        public void OnGet(int id)
        {
            Pizza = _service.GetById(id);
        }

        public IActionResult OnPostSlet(int id)
        {
            _service.Delete(id);
            return RedirectToPage("Index");
        }

        public IActionResult OnPostFortryd()
        {
            return RedirectToPage("Index");
        }
    }
}

ClassDemoPizzaApp/Pages/Pizzas/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ClassDemoPizzaApp.Pages.Pizzas
{
    public class EditModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ClassDemoPizzaApp/Pages/Pizzas/Index.cshtml.cs
using ClassDemoPizzaApp.services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PizzaLib.model;

namespace ClassDemoPizzaApp.Pages.Pizzas
{
    public class IndexModel : PageModel
    {
        /*
         * modtage dependency injection
         */
        private IPizzaRepositoryService _service;

        public IndexModel(IPizzaRepositoryService service)
        {
            _service = service;
        }


        /*
         * Properties til viewet
         */
        public List<Pizza> Pizzaer { get; set; }

        public void OnGet()
        {
            Pizzaer = _service.GetAll();
        }
    }
}

ClassDemoPizzaApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ClassDemoPizzaApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ClassDemoPizzaApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ClassDemoPizzaApp/Pages/Pizzas/Create.cshtml
@page
@model ClassDemoPizzaApp.Pages.Pizzas.CreateModel
@{
}
<h1>Opret en ny Pizza</h1>

<div class="row">
    <div class="col-md-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="@Model.Id" class="control-label">Medlems Id</label><br>
                <input asp-for="@Model.Id" class="form-control" /><br>
                <span asp-validation-for="@Model.Id" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Navn</label><br>
                <input asp-for="@Model.Navn" class="form-control" /><br />
                <span asp-validation-for="@Model.Navn" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Pris</label><br>
                <input asp-for="@Model.Price" class="form-control" /><br />
                <span asp-validation-for="@Model.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Pris</label><br>
                <select   asp-for="Slags" class="form-control">
                    @foreach (var pt in Model.PizzaTyper)
                    {
                        <option value="@pt">@pt</option>
                    }
                </select>
            </div>


            <div class="form-group">
                <input type="submit" value="Opret" />
            </div>

        </form>
    </div>
</div>

ClassDemoPizzaApp/Pages/Pizzas/Delete.cshtml
@page
@model ClassDemoPizzaApp.Pages.Pizzas.DeleteModel
@{
}
<h1>Slet en Pizza</h1>

<table class="table">
    <thead>
        <th></th>
        <th></th>
    </thead>
    <tbody>
        <tr>
            <td>Id</td>
            <td>@Model.Pizza.Id</td>
        </tr>
        <tr>
            <td>Navn</td>
            <td>@Model.Pizza.Name</td>
        </tr><tr>
            <td>Pris</td>
            <td>@Model.Pizza.Pris</td>
        </tr>
        
    </tbody>
</table>

<form method="post">
    <div class="form-group">
        <input type="submit" value="Slet Pizza" asp-page-handler="Slet" asp-route-id="@Model.Pizza.Id" class="btn btn-danger" />
    
        <input type="submit" value="Fortryd" asp-page-handler="Fortryd" class="btn btn-primary" />
    </div>
</form>

ClassDemoPizzaApp/Pages/Pizzas/Edit.cshtml
@page
@model ClassDemoPizzaApp.Pages.Pizzas.EditModel
@{
}

ClassDemoPizzaApp/Pages/Pizzas/Index.cshtml
@page
@using PizzaLib.model;
@model ClassDemoPizzaApp.Pages.Pizzas.IndexModel
@{
}

<h1>Liste af Pizza</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Navn</th>
            <th>Pris</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model.Pizzaer)
        {
            <tr>
                <td>@p.Id</td>
                <td>@p.Name</td>
                <td>@p.Pris</td>
                @if(p is PizzaEnum)
                {
                    PizzaEnum pe = p as PizzaEnum;
                    <td>@pe.Slags</td>
                }
                else
                {
                    <td></td>
                }
                
                <td><a asp-page="Delete" asp-route-id="@p.Id">Delete</a> | <a asp-page="Edit" asp-route-id="@p.Id">Edit</a></td>
            </tr>
        }
    </tbody>
</table>

<p></p>
<p></p>
<form method="get">
    <button asp-page="Create" class="btn btn-primary">Opret Pizza</button>
</form>

ClassDemoPizzaApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClassDemoPizzaApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClassDemoPizzaApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ClassDemoPizzaApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ClassDemoPizzaApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>